name: Release

on:
  release:
    types: [created, published]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    if: github.event.action == 'created'
    
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build source distribution
        run: uv build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/

  attach-to-release:
    name: Attach to release
    runs-on: ubuntu-latest
    needs: build
    if: github.event.action == 'created'
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/*.tar.gz
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: ${{ github.event.release.prerelease }}

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.event.action == 'published'

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build source distribution
        run: uv build --sdist

      # - name: Publish to PyPI
      #   run: |
      #     uv publish --token ${{ secrets.PYPI_API_TOKEN }}
